apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-rtmp
  namespace: openshift-gitops
spec:
  destination:
    namespace: nginx-rtmp
    server: https://$MICROSHIFT_IP:6443
  project: default
  source:
    path: nginx-rtmp/manifest/
    repoURL: https://github.com/yd-ono/AI-for-edge-microshift-demo
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace: true
