apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry-edge
  namespace: openshift-gitops
spec:
  destination:
    namespace: registry
    server: https://$MICROSHIFT_IP:6443
  project: default
  source:
    path: local-registry-deploy
    repoURL: https://github.com/yd-ono/AI-for-edge-microshift-demo
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
