apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-for-edge

resources:
- namespace.yaml
- serviceaccount.yaml
- clusterrolebinding.yaml
- deployment.yaml
- route.yaml
- service.yaml
