FROM quay.io/rbohne/ai-for-edge-microshift-demo:cpu-only AS TRAINER

ADD data/ /data/
ADD model-training.py /data/

WORKDIR /data/

RUN python3 /data/model-training.py

FROM registry.access.redhat.com/ubi9/ubi-micro:latest

COPY --from=TRAINER /data/model.data /src/
ADD copy-content.sh /
ENTRYPOINT "/copy-content.sh"