FROM registry.fedoraproject.org/fedora-minimal:38

RUN dnf install -y --setopt=install_weak_deps=0 \
    python3 python3-flask dlib python3-dlib python3-opencv \
    python3-pillow python3-pip python3-numpy python3-setuptools python3-requests
RUN pip3 install face_recognition

CMD ["echo", "This is a base image ;-)"]