FROM registry.access.redhat.com/ubi9/ubi-minimal

COPY requirements.txt /

RUN microdnf update && microdnf --disableplugin subscription-manager -y install cmake gcc gcc-c++ python python-devel python-pip libglvnd-glx && \
    microdnf clean all

RUN pip3 install -U pip　&& \
    pip3 install -r requirements.txt && \
    rm -rf ~/.cache/pip

CMD ["echo", "This is a base image ;-)"]
