apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registry
  name: registry
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: registry
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: registry
        deployment: registry
    spec:
      containers:
        - image: registry:2.8.1
          imagePullPolicy: IfNotPresent
          name: registry
          ports:
            - containerPort: 5000
              protocol: TCP
          volumeMounts:
          - mountPath: /var/lib/registry
            name: storage
          env:
          - name: "REGISTRY_COMPATIBILITY_SCHEMA1_ENABLED"
            value: "TRUE"
        - name: webui
          image: joxit/docker-registry-ui:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: "SINGLE_REGISTRY"
            value: "true"
          - name: "NGINX_PROXY_PASS_URL"
            value: "http://localhost:5000"
          - name: NGINX_LISTEN_PORT
            value: "8080"
      securityContext:
        runAsUser: 101          
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: registry
      serviceAccount: registry
      serviceAccountName: registry

